[workspace]
resolver = "2"
members = [
    "crates/hikaru_core",
    "crates/hikaru_transport",
    "crates/hikaru_audio_engine",
    "crates/hikaru_sequencer",
    "crates/hikaru_dsp",
    "crates/hikaru_plugin_host",
    "crates/hikaru_midi",
    "crates/hikaru_gui",
    "crates/hikaru_audio_drivers",
]

[workspace.dependencies]
clack-host = "0.2"
clack-extensions = { version = "0.2", features = ["gui", "clack-host", "raw-window-handle_06", "timer", "posix-fd", "log"] }
vst3-host = "0.1"

[profile.dev]
debug = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[patch.crates-io]
vst3-host = { path = "vst3-host-patched" }