[package]
name = "hikaru_plugin_host"
version = "0.1.0"
edition = "2021"

[dependencies]
hikaru_core = { path = "../hikaru_core" }
clack-host = { workspace = true }
clack-extensions = { workspace = true }
vst3-host = { workspace = true }
raw-window-handle = "0.6"
winit = "0.29"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13", features = ["allow-unsafe-code", "dl-libxcb"] }
